def label = "worker-${UUID.randomUUID().toString()}"
def buildNum = "${BUILD_NUMBER}"
def appName = "istio-api-gateway"
def registry  = "${MY_NCR_URL}"
def githubCredential = "github-credential"
def registryCredential = "ncr-credential" 
def githubURL = "${MY_MERCURY_REPO_URL}"

podTemplate(label: label, containers: [
    containerTemplate(name: 'git', image: 'alpine/git', command: 'cat', ttyEnabled: true),
    containerTemplate(name: 'kaniko', image: 'gcr.io/kaniko-project/executor:v1.6.0-debug', command: 'sleep', args: '99d',ttyEnabled: true)
],
volumes: [
  hostPathVolume(mountPath: '/kaniko/.docker', hostPath: '/kaniko/.docker')
]) {
    node(label) {
        stage('Clone repository') {
            container('git') {
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/master']],
                    userRemoteConfigs: [
                        [url: "$githubURL", credentialsId: "$githubCredential"]
                    ],
                ])
            }
        }
        stage('Build docker image') {
            container('kaniko') {
                withDockerRegistry([ credentialsId: "$registryCredential", url: "http://$registry" ]) {
                    sh 'pwd'
                    sh "ls ./$appName"
                    sh "/kaniko/executor -f `pwd`./$appName/Dockerfile -c `pwd` --insecure --skip-tls-verify --cache=true --destination=$registry/$appName:$buildNum"
                    // sh "docker build -t $registry/$appName:$buildNum -f ./$appName/Dockerfile ."
                }
            }
        }
        //  stage('Push docker image') {
        //     container('docker') {
        //         withDockerRegistry([ credentialsId: "$registryCredential", url: "http://$registry" ]) {
        //             docker.image("$registry/$appName:$buildNum").push()
        //         }
        //     }
        // }
    }
}